name: cdp
version: 0.0.1.0
synopsis: A library for the Chrome Devtools Protocol (CDP)
description:
  "
  Chrome Devtools Protocol: https://chromedevtools.github.io/devtools-protocol/

  README: <https://github.com/arsalan0c/cdp-hs>
  
  Examples: <https://github.com/arsalan0c/cdp-hs/examples>
  "
author: Arsalan Cheema
maintainer: Arsalan Cheema
github: arsalan0c/cdp-hs
category: Package.Category
license: BSD-3-Clause

extra-doc-files:
  - README.md

library:
  source-dirs: 
    - src
    - gen

dependencies:
  - base  ==4.14.3.0
  - aeson ==1.5.6.0
  - text  ==1.2.4.1
  - bytestring ==0.10.12.0
  - containers ==0.6.5.1
  - data-default ==0.7.1.1
  - http-conduit ==2.3.8
  - mtl ==2.2.2
  - network-uri ==2.6.4.1
  - extra ==1.7.9
  - text ==1.2.4.1
  - vector ==0.12.3.1
  - websockets ==0.12.7.3
  - random ==1.2.0
  - monad-loops ==0.4.3
  - data-default ==0.7.1.1
  - process ==1.6.13.2
  - filepath ==1.4.2.1
  - directory ==1.3.6.0

executables:
  cdp-gen:
    source-dirs: gen
    main: Main.hs
    default-extensions:
      - Strict
  
  cdp-example-print-page:
    source-dirs: examples
    main: print-page.hs
    dependencies:
      - cdp
      - base64-bytestring

  cdp-example-subscribe:
    source-dirs: examples
    main: subscribe.hs
    dependencies:
      - cdp

  cdp-example-open-twitter:
    source-dirs: examples
    main: open-twitter.hs
    dependencies:
      - cdp

  cdp-example-endpoints:
    source-dirs: examples
    main: endpoints.hs
    dependencies:
      - cdp
      - blaze-html
      - blaze-markup
      - utf8-string

  cdp-example-sessions:
    source-dirs: examples
    main: sessions.hs
    dependencies:
      - cdp

  cdp-example-har:
    source-dirs: examples
    main: export-har.hs
    dependencies:
      - cdp
      - har

tests:
  cdp-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - cdp
      - hspec
