name: cdp
version: 0.0.2.0
synopsis: A library for the Chrome Devtools Protocol
description:
  "
  A library for the Chrome Devtools Protocol (CDP).
  It provides access to Chrome, enabling tasks such as printing a page or opening a tab.

  
  Chrome Devtools Protocol: <https://chromedevtools.github.io/devtools-protocol/>

  
  README: <https://github.com/arsalan0c/cdp-hs>

  
  Examples: <https://github.com/arsalan0c/cdp-hs/examples>
  "
author: Arsalan Cheema
maintainer: Arsalan Cheema
github: arsalan0c/cdp-hs
category: Package.Category
license: BSD-3-Clause
verbatim:
  cabal-version: 3.0

extra-doc-files:
  - README.md

library:
  source-dirs:
    - src
    - gen

dependencies:
- aeson                             >= 1.5.6 && < 3
- base                              >= 4.14.3 && < 4.17
- bytestring                        >= 0.10.12 && < 0.12
- containers                        >= 0.6.4 && < 0.7
- text                              >= 1.2.4 && < 1.3
- random                            >= 1.2.0 && < 1.3
- mtl                               >= 2.2.2 && < 2.3
- vector                            >= 0.12.3 && < 0.13
- data-default                      >= 0.7.1 && < 0.8
- directory                         >= 1.3.6 && < 1.4
- filepath                          >= 1.4.2 && < 1.5
- extra                             >= 1.7.9 && < 1.8
- process                           >= 1.6.13 && < 1.7
- http-conduit                      >= 2.3.8 && < 2.4
- network-uri                       >= 2.6.4 && < 2.7
- monad-loops                       >= 0.4.3 && < 0.5
- websockets                        >= 0.12.7 && < 0.13

executables:
  cdp-gen:
    source-dirs: gen
    main: Main.hs
    default-extensions:
      - Strict
  
  cdp-example-print-page:
    source-dirs: examples
    main: print-page.hs
    dependencies:
      - cdp
      - base64-bytestring                 >= 1.1.0 && < 1.3

  cdp-example-subscribe:
    source-dirs: examples
    main: subscribe.hs
    dependencies:
      - cdp

  cdp-example-open-twitter:
    source-dirs: examples
    main: open-twitter.hs
    dependencies:
      - cdp

  cdp-example-endpoints:
    source-dirs: examples
    main: endpoints.hs
    dependencies:
      - cdp
      - blaze-html                        >= 0.9.1 && < 0.10
      - blaze-markup                      >= 0.8.2 && < 0.9
      - utf8-string                       >= 1.0.2 && < 1.1

  cdp-example-sessions:
    source-dirs: examples
    main: sessions.hs
    dependencies:
      - cdp
      
tests:
  cdp-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - cdp
      - hspec
