name: cdp
version: 0.0.1.0
synopsis: A library for the Chrome Devtools Protocol (CDP)
description:
  "
  Chrome Devtools Protocol: https://chromedevtools.github.io/devtools-protocol/

  README: <https://github.com/arsalan0c/cdp-hs>
  
  Examples: <https://github.com/arsalan0c/cdp-hs/examples>
  "
author: Arsalan Cheema
maintainer: Arsalan Cheema
github: arsalan0c/cdp-hs
category: Package.Category
license: MIT

extra-doc-files:
  - README.md

library:
  source-dirs: 
    - src
    - gen

dependencies:
  - base >= 4.16 && <= 4.17
  - aeson
  - text
  - bytestring
  - containers
  - data-default
  - http-conduit
  - mtl
  - network-uri
  - extra
  - text
  - vector
  - websockets
  - random
  - monad-loops
  - data-default
  - process
  - filepath
  - directory

executables:
  cdp-gen:
    source-dirs: gen
    main: Main.hs
    default-extensions:
      - Strict
  
  cdp-example-print-page:
    source-dirs: examples
    main: print-page.hs
    dependencies:
      - cdp
      - base64-bytestring

  cdp-example-subscribe:
    source-dirs: examples
    main: subscribe.hs
    dependencies:
      - cdp

  cdp-example-open-twitter:
    source-dirs: examples
    main: open-twitter.hs
    dependencies:
      - cdp

  cdp-example-endpoints:
    source-dirs: examples
    main: endpoints.hs
    dependencies:
      - cdp
      - blaze-html
      - blaze-markup
      - utf8-string

  cdp-example-sessions:
    source-dirs: examples
    main: sessions.hs
    dependencies:
      - cdp


tests:
  cdp-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - cdp
      - hspec
