name: cdp
version: 0.0.1.0
synopsis: Project synopsis
description: See README at <https://github.com/arsalan0c/cdp-hs>
author: Arsalan Cheema
github: arsalan0c/cdp-hs
category: Package.Category
license: BSD-3-Clause

extra-doc-files:
  - README.md

library:
  source-dirs: src

dependencies:
  - base
  - aeson
  - text
  - bytestring
  - containers
  - data-default
  - http-conduit
  - mtl
  - network-uri
  - extra
  - text
  - vector
  - websockets
  - casing
  - random
  - monad-loops
  - data-default
  - process

executables:
  cdp-gen:
    source-dirs: gen
    main: Main.hs
    default-extensions:
      - Strict
    dependencies:
      - containers
      - casing
      - filepath
      - directory

  cdp-example-print-page:
    source-dirs: examples
    main: PrintPage.hs
    dependencies:
      - cdp

tests:
  cdp-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - cdp
      - hedgehog
