name: "build"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/**/*"
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14.1
    - uses: browser-actions/setup-chrome@latest
    - name: cdp build
      run: |
        chromium --headless --remote-debugging-port=9222 http://wikipedia.com &
        sleep 5
        nix-build --attr exe

