name: "build"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/**/*"
jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14.1
    - name: cdp build
      run: |
        docker run -d -p 9222:9222 -it --security-opt seccomp=.github/workflows/chrome.json justinribeiro/chrome-headless
        docker ps | grep chrome
        nix-build --attr exe

