name: "build"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/**/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14.1
    - name: cdp build
      shell: bash
      run: |
        docker run -d --network '${{ job.container.network }}'' -it --security-opt seccomp=.github/workflows/chrome.json justinribeiro/chrome-headless
        docker ps | grep chrome
        curl 127.0.0.1:9222
        nix-build --attr exe

