name: "build"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14.1
    - name: cdp-gen build
      run: nix-build --attr exe
    - name: generate cdp library
      run: ./result/bin/gen-exe
    # Out of memory:
    # - name: cdp build
    #   working-directory: cdp
    #   run: nix-build --attr exe

