name: "build"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/**/*"
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14.1
    - uses: browser-actions/setup-chrome@latest
    # - uses: dorny/paths-filter@v2
    #   id: filter
    #   with:
    #     filters: |
    #       cdp:
    #         - 'cdp/**/*'
    - name: run chrome
      id: rc
      run: chrome --remote-debugging-port=9222 http://wikipedia.com &
    - name: cdp-gen build
      id: cgb
      if: steps.rc.outcome == 'success'
      run: nix-build --attr exe
    - name: generate cdp library
      id: gc
      if: steps.cgb.outcome == 'success'
      run: ./result/bin/cdp-gen
    # Takes too long:
    # - name: cdp build
    #   if: steps.gc.outcome == 'success' && steps.filter.outputs.cdp == 'true'
    #   working-directory: cdp
    #   run: nix-build --attr exe

