name: "build"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/**/*"
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14.1
    - name: cdp build
      run: |
        docker run -d -p 9222:9222 justinribeiro/chrome-headless
        sleep 5
        nix-build --attr exe

