name: "build"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/**/*"
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    services:
      chrome:
        image: justinribeiro/chrome-headless
        options: --name chrome
        ports:
         - 9222:9222
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: cachix/install-nix-action@v14.1
    - name: cdp build
      run: |
        docker run --name chrome -d -p 9222:9222
        sleep 5
        nix-build --attr exe

